In [230]:
#Lets get the matrices and vectors
from watermatrices import Amat as A
from watermatrices import Bmat as B
from watermatrices import yvec as y
import numpy as np
import os
import importlib

#Get some functions from external file
cwd = os.getcwd()
os.chdir(r"C:\Users\sjefs\Desktop\Scientific Computing\Functions")
importlib.reload(SC_functions)
import SC_functions as SC
os.chdir(cwd)

# Questions
What do we do with propogating significant digits ? 

# Question a)
## (1) 
We start by creating the infinity norm function

In [89]:

def infinity_norm(M):
    """
    Function for calculating an infinity norm
    _____________________________
    parameters:
    matrix : ndarray
        Some matrix of arbitrary dimensions

    return:
    infinity norm : float
        Value of the infinity norm
    """
    # We create a matrix with only the absolute values. Then we sum each of the rows, and find which row has the largest sum
    return max(np.sum(abs(M), axis = 1))

def infinity_bound(M):
    """
    Function for calculating an infinity bound
    _____________________________
    parameters:
    matrix : ndarray
        Some matrix of arbitrary dimensions

    return:
    infinity bound : float
        Value of the infinity bound
    """
    return infinity_norm(M) * infinity_norm(np.linalg.inv(M))


## (2)
First we make the E and S matrices. Then we calculate the matrixes that combine E and S with omega. Then we use our previously defined functions

In [83]:
#Create the matrix E
E = np.block([[A, B], [B, A]])

#Create the matrix S
S = np.zeros((14,14))
S[0:7, 0:7] = np.eye(7)
S[7:14, 7:14] = -np.eye(7)

#Define omega values
omega = np.array([0.8, 1.146, 1.400])

#Make the matrixes
test_matrixes = [E - x*S for x in omega]

#Calculate the bound
condition_numbers = [infinity_bound(matrix) for matrix in test_matrixes]
print(condition_numbers)

[np.float64(327.81670424209915), np.float64(152679.2687523386), np.float64(227.19443667104446)]


# Question (B)
## (1)

In [88]:
# We already have the infinity bound of E-omega*S. So we just need to calculate the fraction:
delta_omega = 1/2*10**(-3)

def relative_forward_bound(E, S, omega):
    return infinity_bound(E - omega*S) * infinity_norm(delta_omega*S)/infinity_norm(E-omega*S)

result = [relative_forward_bound(E, S, x) for x in omega]
print(result)



[np.float64(0.005220745069573262), np.float64(2.4050352674535698), np.float64(0.0035504027789308675)]


# Question (C)
## (1)  
See function in SC_functions

In [170]:
#np.random.seed(42)
M = np.random.randint(0, 10, (4,4)).astype(float)
test = np.matrix.copy(M)
print(M)


[[4. 4. 9. 3.]
 [5. 6. 8. 0.]
 [5. 6. 2. 7.]
 [4. 8. 4. 8.]]
[[4. 4. 9. 3.]
 [5. 6. 8. 0.]
 [5. 6. 2. 7.]
 [4. 8. 4. 8.]]


## (2)


In [274]:
def forward_substitute(L, b):
    n = len(b)
    x = np.zeros(n)
    for j in range(n):
        if L[j,j] == 0:
            raise ValueError("The diagonal element is zero")
        x[j] = b[j]/L[j,j]
        for i in range(j+1, n):
            b[i] = b[i]-L[i,j]*x[j]
    return x


M = np.random.randint(1, 10, (4,4)).astype(float)
test = np.matrix.copy(M)
b = [1,2,3,4]
result = forward_substitute(M, b)
print(result)

[ 0.14285714  1.71428571 -1.42857143  2.        ]
